#!/bin/sh
# Extract UFOs from .glyphs file then do normal preflight

echo ""
echo "Converting .glyphs to UFO3..."
psfglyphs2ufo source/Harmattan-master.glyphs source

# Continue with normal preflight
./preflight
