#!/bin/sh
# Script for calling multiple routines on a project, typically prior to committing to a repository.

echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/*-Regular.ufo

echo "Check and normalize Regular..."
# Do this before meta sync so we minimize problems in the Bold
psfnormalize -p checkfix=fix source/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/*-RB.designspace

echo "Check and normalize Bold..."
psfnormalize -p checkfix=fix source/*-Bold.ufo

echo "Updating woff metadata file..."
psfmakewoffmetadata -q -n Harmattan -i org.sil.fonts source/*-Regular.ufo

echo "preflight completed!"
