#!/bin/sh
# Script for calling multiple routines on a project, typically prior to committing to a repository.

echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/*-Regular.ufo

echo "Check and normalize Regular..."
# Do this before meta sync so we minimize problems in the Bold
psfnormalize -p checkfix=fix source/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/*-RB.designspace

echo "Check and normalize Bold..."
psfnormalize -p checkfix=fix source/*-Bold.ufo

echo "Updating woff metadata file..."
psfmakewoffmetadata -q -n Harmattan -i org.sil.fonts source/*-Regular.ufo

echo "Building internal fea..."
psfmakefea -o source/Harmattan-Regular.ufo/features.fea -l Harmattan-Regular-psfmakefea.log -i source/opentype/master.feax -c source/classes.xml --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/*-Regular.ufo &
psfmakefea -o source/Harmattan-Bold.ufo/features.fea    -l Harmattan-Bold-psfmakefea.log    -i source/opentype/master.feax -c source/classes.xml --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/*-Bold.ufo    &
wait

echo "preflight completed!"
