#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/*-Regular.ufo  &
psffixffglifs -p checkfix=fix source/*-Bold.ufo     &
wait

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/*-RB.designspace

echo "Updating woff metadata file..."
psfmakewoffmetadata -q -n Harmattan -i org.sil.fonts source/*-Regular.ufo

echo "Building internal fea..."
psfmakefea -q -o source/Harmattan-Regular.ufo/features.fea -l Harmattan-Regular-psfmakefea.log -i source/opentype/master.feax -c source/classes.xml --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/*-Regular.ufo &
psfmakefea -q -o source/Harmattan-Bold.ufo/features.fea    -l Harmattan-Bold-psfmakefea.log    -i source/opentype/master.feax -c source/classes.xml --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/*-Bold.ufo    &
wait

echo "preflightff completed!"
