#!/bin/sh
# Extract UFOs from .glyphs file then do normal preflight

echo ""
echo "Converting .glyphs to UFO3..."
if psfglyphs2ufo --nofea source/Harmattan-RB.glyphs source
then
	# Succss. Now fix up the advancewidth of yehbelow-ar
	psfremovegliflibkeys source/Harmattan-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth
	psfremovegliflibkeys source/Harmattan-Bold.ufo    com.schriftgestaltung.Glyphs.originalWidth
	# Continue with normal preflight
	./preflight
else
	# Something went wrong... abort
	echo ""
	echo "psfglyphs2ufo failed ... aborting preflightg."
	echo ""
fi
